project_id = "uzfafbbilxzduvvvtxuy"

[functions.chat]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.text-to-voice]
verify_jwt = false

[functions.realtime-session]
verify_jwt = false
